### ISSUE TITLE
`Aws4Signer` has been marked as deprecated

### ISSUE THREAD

**Issue by reibitto** [acm19/aws-request-signing-apache-interceptor#121]
I was trying to upgrade the aws sdk to version 2.25.69 and now I see a deprecation warning for `Aws4Signer`:
https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/signer/Aws4Signer.html

In the docs it suggests using `software.amazon.awssdk.http.auth.aws.signer.AwsV4HttpSigner`. I didn't investigate too much beyond checking to see if `AwsV4HttpSigner` was a drop-in replacement for `Aws4Signer`, but from what I can tell it's not. I'm not sure how involved the actual solution to this or what the path forward is, but I thought I'd create an issue here to track it or start a discussion for some ideas.

**Comment by dblock** [comment]
Thanks for opening this @reibitto. Try upgrading this repo using `AwsV4HttpSigner` and see what happens?

**Comment by dblock** [comment]
@reibitto There's a PR ready in https://github.com/acm19/aws-request-signing-apache-interceptor/pull/125, test it out?

**Comment by reibitto** [comment]
Oh sorry I forgot to get back to this issue. I haven't deployed our real app with this but I installed the 3.0.0-SNAPSHOT dependency locally and ran a manual test with it and it seems to work fine to me.

Thanks!
