### ISSUE TITLE
Extend copyright to contributors

### ISSUE THREAD

**Issue by dblock** [acm19/aws-request-signing-apache-interceptor#34]
The copyright of this project is currently as follows:

```
Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved. 
```

I propose we ask the copyright owner (Amazon) to release copyright, as follows:

```
Copyright AWS Request Signing Interceptor Contributors.
```

Or remove the year, and extend it to contributors, as follows:

```
Copyright Amazon.com, Inc., its affiliates, or AWS Request Signing Interceptor contributors. All Rights Reserved.
```

**Comment by acm19** [comment]
Is there a standard way to make such request?
> I propose we ask the copyright owner (Amazon) to release copyright
I'm happy to follow do that and/or use the other option in the meanwhile.

**Comment by dblock** [comment]
@acm19 There isn't, but I wanted to surface this to you as the maintainer of this fork. Feel free to email me dblock at amazon dot com if you want to be cc-ed.

**Comment by acm19** [comment]
Done.
