### ISSUE TITLE
Release to maven central

### ISSUE THREAD

**Issue by dblock** [acm19/aws-request-signing-apache-interceptor#35]
Release `io.github.acm19.aws-request-signing-apache-interceptor` to Maven.

Also #23 will make it repeatable and easy.

**Comment by dblock** [comment]
@acm19 I'd be happy to take care of this if you want to give me repo access

**Comment by acm19** [comment]
I haven't been able to catch up but I'm really interested in doing this one. I should be up to date by the end of the week, as well as hopefully actually contribute. If I'm not able to catch up I'll be happy let you take care of it.

**Comment by acm19** [comment]
Project requested: https://issues.sonatype.org/browse/OSSRH-82461

**Comment by dblock** [comment]
As part of this I'd like us to add a RELEASING.md (like [this one](https://github.com/acm19/aws-request-signing-apache-interceptor/blob/master/CHANGELOG.md#203-next)) that has instructions of how to do a release that can be followed by any current/future maintainer. Those would include updating CHANGELOG and version to the next development iteration.

**Comment by acm19** [comment]
:rocket:

**Comment by dblock** [comment]
@acm19 I see https://github.com/acm19/aws-request-signing-apache-interceptor/runs/7308424461?check_suite_focus=true succeeding, but can't find the project in maven central. Are you seeing it in staging? Does it need to be manually published? I think either way add instructions to RELEASING?

**Comment by dblock** [comment]
I just opened https://github.com/acm19/aws-request-signing-apache-interceptor/issues/65 to track

**Comment by acm19** [comment]
I've closed the release, according to the docs in max 2 hours should be indexed, I'll check again tomorrow:

> Once you have successfully closed the staging repository, you can release it by pressing the Release button. This will move the components into the release repository of OSSRH where it will be synced to the Central Repository.

**Comment by dblock** [comment]
It's up!

https://s01.oss.sonatype.org/#nexus-search;quick~aws-request-signing-apache-interceptor

The maven central and stuff will take some time to update, I'll add badges soon.

**Comment by acm19** [comment]
This is indeed annoying, their bot updated my ticket yesterday with this info:
> Central sync is activated for io.github.acm19. After you successfully release, your component will be available to the public on Central https://repo1.maven.org/maven2/, typically within 30 minutes, though updates to https://search.maven.org/ can take up to four hours.

I can confirm it's available: https://repo1.maven.org/maven2/io/github/acm19/aws-request-signing-apache-interceptor/2.1.1/ and it's downloadable by Maven, but it doesn't seem to be indexed for search yet. I'm not home today, but I'll create a ticket for the sonatype guys as soon as I'm back if it's still not searchable.

**Comment by acm19** [comment]
Ticket to asking for support on the repo no being searchable: https://issues.sonatype.org/browse/OSSRH-82665. @dblock are you able to see the tickets?
