### ISSUE TITLE
Create convention on how to write commit messages

### ISSUE THREAD

**Issue by acm19** [acm19/aws-request-signing-apache-interceptor#47]
This https://github.com/acm19/aws-request-signing-apache-interceptor/pull/42#discussion_r916262158 highlighted the importance of having consistent commit messages, specially titles to help automating the process of generating a CHANGELOG.

Having an explanation for contributors, specially the title. I propose using Linus Torvalds approach as: https://github.com/torvalds/subsurface-for-dirk/blob/a48494d2fbed58c751e9b7e8fbff88582f9b2d02/README#L88

	Header line: explain the commit in one line (use the imperative)

	Body of commit message is a few lines of text, explaining things
	in more detail, possibly giving some background about the issue
	being fixed, etc etc.

	The body of the commit message can be several paragraphs, and
	please do proper word-wrap and keep columns shorter than about
	74 characters or so. That way "git log" will show things
	nicely even when it's indented.

At the end of the header line there should be a reference to the issue (if any) surrounded by parenthesis (to be consistent with the way GitHub does it), e.g. `Create convention (#47)`.

Consistency with the tense is rare on the industry logs therefore imperative header is specially relevant. Examples were there is no consistency: https://github.com/aws/aws-sdk-java-v2/blob/HEAD/CHANGELOG.md#%E2%80%8B217225-2022-07-05. This takes into account that some automatic update bots like Renovate can get the change log and add it to the PR based on the commits.

**Comment by dblock** [comment]
+1 I think this should go into https://github.com/acm19/aws-request-signing-apache-interceptor/blob/master/CONTRIBUTING.md
