### ISSUE TITLE
Where's aws-request-signing-apache-interceptor in Maven?

### ISSUE THREAD

**Issue by dblock** [acm19/aws-request-signing-apache-interceptor#65]
Now that we have done #35 we need to be able to find what we published ;)

https://mvnrepository.com/search?q=aws-request-signing-apache-interceptor isn't turning up.

I see snapshots in https://s01.oss.sonatype.org/#nexus-search;quick~aws-request-signing-apache-interceptor, but no released artifacts. I imagine that CI published to https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/io/github/acm19/aws-request-signing-apache-interceptor, but I cannot see it (permissions).

1. Do we still have to promote the library from staging to releases, manually?  
2. If (1), document in RELEASING.md.
3. Once we find the release in maven, add how to use it into README.
4. We should reduce bus factor of who has access to the staging repo. Add dblock (I think it needs a JIRA in https://issues.sonatype.org/browse/OSSRH-33832)?

**Comment by acm19** [comment]
Let's reopen this one: https://central.sonatype.org/publish/release/#locate-and-examine-your-staging-repository. Apparently for full automation we'll need to use the Nexus Staging Maven Plugin:
> Note that deploying with the Nexus Staging [Maven](https://central.sonatype.org/publish/publish-maven/) plugin or [Ant](https://central.sonatype.org/publish/publish-ant/) tasks will, by default, automatically attempt to close the staging repository upon deployment and can be used to release the staging repository from the command line as well. This allows you to avoid logging into the OSSRH user interface altogether. More details can be found in the Maven and Ant sections of this guide.

**Comment by dblock** [comment]
We have https://issues.sonatype.org/browse/OSSRH-82461 open because the project is still not coming up in search.

**Comment by dblock** [comment]
It's showing up today! https://search.maven.org/artifact/io.github.acm19/aws-request-signing-apache-interceptor
