### ISSUE TITLE
Replace GitHub issue labels

### ISSUE THREAD

**Issue by dblock** [acm19/aws-request-signing-apache-interceptor#66]
I like colorful labels and dislike the built in ones. 

How about these as an alternative?

```
ghi label "bug?" -c "#fbca04" -- $repo
ghi label "confirmed bug" -c "#e10c02" -- $repo
ghi label "new feature" -c "#009800" -- $repo
ghi label "chore" -c "#207de5" -- $repo
ghi label "question" -c "#5319e7" -- $repo
```

I can delete existing labels and create these, but don't have access 😢 

Feel free to close if you disagree and think we should stick with defaults.

**Comment by dblock** [comment]
Actually I think we should stick with defaults ;)

**Comment by acm19** [comment]
That was short lived :) I don't have a strong opinion either way.

**Comment by dblock** [comment]
I flip flopped on it.
