### ISSUE TITLE
Add Terraform directory with small OpenSearch cluster for testing

### ISSUE THREAD

**Issue by acm19** [acm19/aws-request-signing-apache-interceptor#73]
Add a `infra` directory with a Terraform project to run a small cluster for testing purposes by the contributors. Easy to setup and tear down.

**Comment by acm19** [comment]
Good point. The way I see it in this context:

Advantages of going TF:
* Drift detection (specially useful for testing or long lived test projects).
* Speed, calling API without CFN overhead.
* Declarative.

Advantages of CDK:
* No need for backend.

I'm happy to go the CDK way for idividual collaborators cluster, I wouldn't even mind CFN directly, because of no backend needed. If at some point we need a long lived common cluster then I'd def chose Terraform, specially because of the drift detection.

**Comment by dblock** [comment]
Since I am not writing it, I only have opinions ;)

**Comment by acm19** [comment]
Potential user are important ;)

**Comment by dblock** [comment]
Related, are you thinking of launching a new OpenSearch cluster in AWS on demand for integration tests? Those clusters aren't that fast to come up. But maybe it's sufficient to run test on anything merged onto master even if that's slow ...

**Comment by acm19** [comment]
Cluster are slow to create and tear down. I'm planning to make it easy for someone that need to work on a bug or feature to easily spin it up and tear it down for development. Free tier for OpenSearch is for 12 months only.
