### ISSUE TITLE
Fully automate the release process

### ISSUE THREAD

**Issue by acm19** [acm19/aws-request-signing-apache-interceptor#84]
Description:
Automatically close and release as part of the Maven deployment stage using `nexus-staging-maven-plugin` as described here: https://central.sonatype.org/publish/publish-maven/#nexus-staging-maven-plugin-for-deployment-and-release.

Expected outcome:
1. Releasing doesn't require any manual step.
2. All contributors can release without requiring intervention from a single person.

**Comment by dblock** [comment]
Thanks for releasing 2.2.0 @acm19 !

**Comment by dblock** [comment]
I'll take on documenting the manual parts of this for now once I get maven access.

**Comment by acm19** [comment]
This one is about releasing with a fully automated process, unfortunately I've been swamped lately, so haven't been able to make the changes :(
