### ISSUE TITLE
Enforce GitHub issues in checkstyle configuration

### ISSUE THREAD

**Issue by dblock** [acm19/aws-request-signing-apache-interceptor#96]
Trying to change checkstyle.xml `TodoComment` doesn't seem to have any effect when running `mvn validate -Pcheckstyle`.

Also note that `mvn checkstyle:check` doesn't use that configuration.

**Comment by acm19** [comment]
> Trying to change checkstyle.xml `TodoComment`

What's not working exactly, this works for me. By default checkstyle `TodoComment` matches only `TODO` case sensitive.

> Also note that mvn checkstyle:check doesn't use that configuration.

This is by design, but the GitHub job uses `validate` with the proper profile, so it properly validate checkstyle. For speed locally you can use `make checkstyle`.
